"""init

Revision ID: 4fa87af69893
Revises: 
Create Date: 2023-05-24 15:35:38.991809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa87af69893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbol.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_bar')
    op.drop_table('symbol')
    # ### end Alembic commands ###
